# /frontend/Dockerfile

# Use the official Node.js image as a base
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port your app runs on
EXPOSE 5173

# Command to run the application
CMD ["npm", "run", "preview"]
